### ISSUE TITLE
Out of curiosity

### ISSUE THREAD

**Issue by giuliboy** [mico-micic/vzug-api#2]
Hi guys, 

i'm building a kitchen right now. Naturally, all the devices are from V-Zug...
I am looking on how to integrate them into my existing HA setup and came across your py lib.

Could not see any "commands" on the API, just some GETters. 
Is there some limitation on the API level that you experienced and will prevent us from having control over the machines or did you just not dig deep enough?

Cheers,
G

**Comment by mico-micic** [comment]
Thank you very much for your contribution! Sorry for the late reply, for unknown reasons I didn't receive notifications from github.. I think there should be no limitations to implement also Commands. We just haven't had time to try it yet :)

By the way: I wrote the API to implement a HA plug-in: https://github.com/mico-micic/core (HA with implement V-Zug Plug-In, now a little behind the current HA development. I should update it again)

**Comment by supaeasy** [comment]
Could you provide this as an integration, be it via HACS or via the official release? Or provide information on how to integrate this in an existing HA installation? That would be awesome!

**Comment by mico-micic** [comment]
My initial idea was to contribute an "official" plug-in once I have implemented the supported for more than just 2-3 devices. But that is actually not the case. Maybe I will create a HACS version as an interim solution.

In the meantime you can integrate it manually in your HA installation by the following steps: 
(testet with HA version 2023.5.4)

- Clone the forked HA repository containing the plug-in:  `git clone https://github.com/mico-micic/core.git`
- ` cd core`
- Checkout the feature branch: `git checkout feature/vzug-integration`
- copy the complete folder `homeassistant/components/vzug` to your HA directory `custom_components/vzug `
- Restart HA

If something went wrong, please post the log files so I can help you get it working.

**Comment by twolf78** [comment]
There is already an integration available: https://github.com/siku2/hass-vzug

Independent from this library of course, the curse of small open source projects...

**Comment by supaeasy** [comment]
THANK YOU!
It works very fine.

**Comment by mico-micic** [comment]
Thank you @twolf78, I have already seen your integration. I will close this issue here. This api here is also used for other integrations (not just home assistant), so it makes sense to keep it.
